# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brendan Coffey
email: bmc@section9.net
description: > # this means to ignore newlines until "baseurl:"
  I'm Brendan. I'm a skier, backpacker, climber, software engineer,
  native New Englander transplant to California. In the fall of
  2015, I left Silicon Valley to travel. This little blog is where
  I will record my travels.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leetbmc.github.io/" # the base hostname & protocol for your site
twitter_username: leetbmc
github_username:  leetbmc

# Build settings
markdown: kramdown

gems:
  - jekyll-feed

